### ISSUE TITLE
ContentDecodingFailed

### ISSUE THREAD

**Issue by lbenner07** [NadyaNayme/job-gauges#89]
![image](https://github.com/user-attachments/assets/f48b2e12-84fa-4c50-aab1-f9f9292a26a8)
No changes made to PC. Stopped working around 4 days ago.

**Comment by NadyaNayme** [comment]
This happened to me at some point during testing but I can't recall what fixed it. It can be caused by a few different things and, at least in theory, shouldn't even be a problem for Alt1's Chromium. 

As for troubleshooting - can try upgrading to Alt1 1.6.0 if you're still on Alt1 1.5.6.

**Comment by lbenner07** [comment]
Deleting and regenerating the secret key solved the issue. Thanks for the help!

**Comment by NadyaNayme** [comment]
I greatly appreciate you reporting back that it worked. :) Thank you!
